/** Shared Jamaat affiliation options for registration forms (volleyball, soccer, etc.). */
export const JAMAAT_AFFILIATION_OPTIONS = [
  "Anjuman-e-Burhani, Seattle",
  "Anjuman-e-Badri, New York",
  "Anjuman-e-Badri, Ottawa",
  "Anjuman-e-Burhanee, Los Angeles",
  "Anjuman-e-Burhani, Austin",
  "Anjuman-e-Burhani, New Jersey",
  "Anjuman-e-Burhani, Toronto",
  "Anjuman-e-Ezzi, Boston",
  "Anjuman-e-Ezzi, Washington D.C.",
  "Anjuman-e-Fakhri, Minneapolis",
  "Anjuman-e-Fakhri, Missisauga",
  "Anjuman-e-Fakhri, Philadelphia",
  "Anjuman-e-Fakhri, South Jersey",
  "Anjuman-e-Hakimi, Bakersfield",
  "Anjuman-e-Hakimi, Montreal",
  "Anjuman-e-Hasani, Poconos",
  "Anjuman-e-Husaini, Portland",
  "Anjuman-e-Husami, Atlanta",
  "Anjuman-e-Husami, South Carolina",
  "Anjuman-e-Imadi, Sugarland",
  "Anjuman-e-Jamali, Miami",
  "Anjuman-e-Jamali, North Carolina",
  "Anjuman-e-Jamali, San Jose",
  "Anjuman-e-Jamali, Vancouver",
  "Anjuman-e-Mohammedi, San Antonio",
  "Anjuman-e-Mohammedi, San Diego",
  "Anjuman-e-Mohammedi, Virginia",
  "Anjuman-e-Najmi, Dallas",
  "Anjuman-e-Najmi, Detroit",
  "Anjuman-e-Najmi, San Francisco",
  "Anjuman-e-Qutbi, Orange County",
  "Anjuman-e-Saifee, Chicago",
  "Anjuman-e-Saifee, Edmonton",
  "Anjuman-e-Saifee, Woodlands",
  "Anjuman-e-Shujaee, Houston",
  "Anjuman-e-Shujahee, North Chicago",
  "Anjuman-e-Taheri, Columbus",
  "Anjuman-e-Taheri, Plano",
  "Anjuman-e-Vajihi, Calgary",
  "Anjuman-e-Vajihi, Tampa",
  "Non-US/Canada jamaat",
] as const;
